### ISSUE TITLE
Documentar os dados consumidos pela API Flask

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#12]
migrado do taiga: https://tree.taiga.io/project/lappis-ecossistema-software-livre/us/118?milestone=169205

**Comment by joenio** [comment]
@arthurTemporim @joaorobson como tá isso aqui?

**Comment by arthurTemporim** [comment]
Esta pronto. Foi acidionado o tópico de Documentação no [README](https://github.com/lappis-unb/salic-api/blob/master/README.rst) tanto do [SWAGER](http://api.salic.cultura.gov.br/doc/) quanto do [SPHINX](https://salic-api.readthedocs.org/pt/latest/).
