### ISSUE TITLE
Documentar os dados do app/api Proposta

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#13]
migrado do taiga: https://tree.taiga.io/project/lappis-ecossistema-software-livre/us/119?milestone=169205

**Comment by LucianoPC** [comment]
Primeiros Dados da proposta:
    - Nome da proposta
    - Resumo da proposta cultural
    - Data fixa [Não, Sim]
    - Agencia bancária
    - É proposta audiovisual [Não, Sim]
    - Plano execução imediata [Várias opções]
    - Data inicio
    - Data final
    - Prorrogação Automática [Sim, Não]
    - Número do Ato
    - Data do Ato
    - Esfera do Ato
    - Objetivos geral e específico
    - Justificativa

**Comment by joenio** [comment]
@LucianoPC @fabio1079 isso tá finalizado? a documentação é esta que está no comentário acima? está em algum outro local? wiki? git?
