### ISSUE TITLE
Solicitar acesso ao banco do SALIC via VPN

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#15]
migrado do taiga: https://tree.taiga.io/project/lappis-ecossistema-software-livre/us/121?milestone=169205

**Comment by seatecnologia** [comment]
Prezados, me enviaram um email sobre o acesso e vou testar.

Att,

Edson

**Comment by edsonma** [comment]
Pessoal, consegui acessar a VPN por meio do login do matheus faria. 

O banco consegui acesasr pelo login que me passaram no email.

Aproveitando para colocar aqui algumas informações de alguns bancos que são usados pelo salic-api

+---------+------------------------------------+
| SAC         |   669,806.63 MB MINC\SQLSRVC    |
| Agentes  |       706.00 MB MINC\SQLSRVC        |
| Tabelas   |     2,294.00 MB MINC\SQLSRVC      |
+---------+------------------------------------+

**Comment by marcosronaldo** [comment]
Ainda não temos acesso todos os bancos necessários para as queries da API salic. Precisamos do acesso ao banco BDCorporativo para prosseguir com várias tarefas.

**Comment by joenio** [comment]
@edsonma @marcosronaldo, creio que o acesso ao banco via VPN está ok, correto? fechando issue.
