### ISSUE TITLE
Checklist Jaiminho

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/EcossistemasSWLivre#24]
Realizar o checklist do projeto 
[Jaiminho](https://github.com/culturagovbr/jaiminho)

Projeto de maillist feito em 2015. Plugin do wordpress e funciona como tema do wordpress.
Requisitos :

* Instrumentação - docker, code climate, travis, etc
* Documentação - técnica/implementação

Objetivo: oferecer como SaaS (orgãos como Funarte, etc)

**Comment by joenio** [comment]
ainda temos pendência em relação a essa demanda?

**Comment by RochaCarla** [comment]
Temos-- eh daquela frente que cada sprint teria uma dupla pra "dockerizar" e fazer o checklists de projetos minc

**Comment by joenio** [comment]
ok, vou organizar isso dentro da frente devops então.

**Comment by guilacerda** [comment]
Checklist concluído. Feito a partir de boas práticas e padrões de software livre.

Foi dado um fork e feito um commit com seu respectivo checklist.
Link para o commit com o checklist: [Jaiminho](https://github.com/guilacerda/jaiminho/commit/0d020a26a22db035d1db977f020ea0cb40c1d6d4)

O repositório está inativo há mais de 1 ano e 3 meses.
