### ISSUE TITLE
Checklist Simec

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/EcossistemasSWLivre#25]
Realizar o checklist no projeto [Simec/Siminc2](https://github.com/culturagovbr/siminc2)

* Desenvolvedores (contatos): Orion, Rafael
* Tem documentação (checar)
* Instrumentação/Checklist

Objetivo: Implantar em outros órgãos

**Comment by joenio** [comment]
@RochaCarla creio que o simec saiu do escopo de atuação do lab, certo? fechando issue.
