### ISSUE TITLE
Checklist Login Cidadão

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/EcossistemasSWLivre#26]
Realizar o Checklist no projeto [Login Cidadão](https://github.com/culturagovbr/id-cultura)

* Utilizado para rodar nosso ID Cultura.

**Comment by guilacerda** [comment]
Checklist concluído. Feito a partir de boas práticas e padrões de software livre.

Foi dado um fork e feito um commit com seu respectivo checklist.
Link para o commit com o checklist: [id-cultura](https://github.com/guilacerda/id-cultura/commit/aad016dbd38d9596f16b70b369358fc8c959900b)

O repositório está inativo há mais de 1 ano e 6 meses.
