### ISSUE TITLE
Checklist PDFA Converter

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/EcossistemasSWLivre#27]
Checklist [PDFA Converter]( https://github.com/culturagovbr/PDFA-Converter)

É uma ferramenta para apoiar/simplificar a digitalização de documentos, que garante atender à certos requisitos e formatos de documentos. A ideia inclusive é eliminar a necessidade do Adobe.

**Comment by guilacerda** [comment]
Checklist concluído. Feito a partir de boas práticas e padrões de software livre.

Foi dado um fork e feito um commit com seu respectivo checklist.
Link para o commit com o checklist: [PDFA-Converter](https://github.com/guilacerda/PDFA-Converter/commit/80d7a6b93ca7d14e72780c95afc78965a564da74)

O repositório está inativo há 6 meses.
