### ISSUE TITLE
Checklist SNC

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/EcossistemasSWLivre#28]
Checklist do projeto [Sistema Nacional de Cultura](https://github.com/culturagovbr/sistema-nacional-cultura)

**Comment by guilacerda** [comment]
Checklist concluído. Feito a partir de boas práticas e padrões de software livre.

Foi dado um fork e feito um commit com seu respectivo checklist.
Link para o commit com o checklist: [SNC](https://github.com/guilacerda/sistema-nacional-cultura/commit/2e83a5c39635aa168098d3ba6f6a889d1491e83e)

O repositório está inativo há 4 meses.
