### ISSUE TITLE
Reunião com o Diego para decidir o futuro do bot

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#32]

**Comment by joenio** [comment]
detalhes "internos da frente" sobre o andamento desta issue em: https://github.com/lappis-unb/minc-rouanet-bot

**Comment by Duerno** [comment]
Durante a reunião, discutiu-se sobre:
- Potenciais do [hubot-natural](https://github.com/RocketChat/hubot-natural);
- Outras tecnologias de criação de bots (como Rasa, AIVA, Botpress e etc);
- Possível integração entre Rasa e Rocket.Chat;
- Próximos passos do projeto Rouana.

Decidiu-se continuar com o hubot-natural para criar uma primeira versão capaz de ser colocada em produção em um curto período de tempo. Após este passo, o projeto passará por uma etapa de avaliação e teste de outras ferramentas de criação de bots.

A reunião aconteceu no dia 17 de janeiro de 2018 no LAPPIS, FGA.
Estavam presentes: Diego Dorgam, Matheus Faria, Felipe Duerno, Matheus Miranda, Joênio Costa e Eduardo Nunes.
