### ISSUE TITLE
Documentação do repositório do hubot-natural

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/EcossistemasSWLivre#38]
- Documentar o processo de configuração do LiveTransfer
- Traduzir documentação do hubot-natural para o inglês
- Adotar solução de documentação para o hubot-natural

**Comment by joenio** [comment]
gente, essa épica está na Sprint 2 e a sprint já acabou, creio que épicas irão durar várias sprints, correto? será que n faz sentido deixar issues do tipo épica sem milestone? sem sprint definida? (idem para as épicas #37 #36 #33 #40)
