### ISSUE TITLE
checklist dos resultados da entrega-01 da frente de pesquisa

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#45]
a frente de pesquisa coletou dados com os alunos do projeto e entregou alguns relatórios (link abaixo), será necessário avaliar cada ponto do relatório, em cada ponto é importante dar feedback e planejar encaminhamentos para aqueles que precisam ser tratados internamente com ações quando for o caso, alguns pontos sugerem mais investigação, outros sugerem tomada de ação para corrigir práticas internas, é importante tratar cada um destes pontos.

* https://github.com/lappis-unb/EcossistemasSWLivre/tree/master/resultados-da-frente-pesquisa/entrega-01-dados-alunos

**Comment by joenio** [comment]
@RochaCarla e @MatheusFaria analisaram os relatórios e fizeram anotações no link abaixo:

* https://docs.google.com/document/d/1zGkHUpecNdogRq4qJtar1hSu0UpHbDOsVQfMYLj2Ovs/edit

é importante materializar as notas do link acima no próprio repositório pois esses links costumam ficar perdidos no oceano de docs

**Comment by joenio** [comment]
ver issue #56

**Comment by MatheusFaria** [comment]
https://github.com/lappis-unb/EcossistemasSWLivre/wiki/Frente-de-Pesquisa
