### ISSUE TITLE
preparar ambiente de homologação para testar e validar o chatbot

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#47]
* a primeira entrega em produção ao minc será o chatbot no site da lei rouanet
* iremos nos reunir no dia 19/03 para testar e validar este ambiente
  * uma vez validado iremos planejar a entrega ao minc em ambiente de produção
  * convidar poppi, peter e maia para ajudar na validação dia 19/03 e documentar a entrega ao minc

**Comment by MatheusFaria** [comment]
Issue duplicada
