### ISSUE TITLE
testar e validar o chatbot em ambiente de homologação

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#48]
* data: 19/03
* horário: à definir
* depende da issue #47

ata da reunião onde surgiu esta atividade:
* https://github.com/lappis-unb/EcossistemasSWLivre/wiki/Reuniao-26-02-2018-COORDENACAO-PESQUISA

**Comment by MatheusFaria** [comment]
Creio que o teste inicial foi feito, mas precisamos discutir novas estratégias de teste #57
