### ISSUE TITLE
Preencher checklist do Tainacan

### ISSUE THREAD

**Issue by MatheusMiranda** [lappis-unb/EcossistemasSWLivre#5]
- Avaliar organização do repositório, formas de colaboração e distribuição do projeto;
- Mapear pontos de melhoria;
- Mapear demandas e documentar pontos importantes;

**Comment by fabio1079** [comment]
# Checklist

## Básico
projeto: Tainacan
repositório: https://github.com/medialab-ufg/tainacan/
linguagem principal: PHP
plataforma (web, mobile, desktop, etc): web

## Readme
posui readme?: Sim
formato do readme (md, txt, rst, etc): Md
badges presentes no readme: None

## Integração contínua
possui testes? Sim?(estão em outro repositório aparentemente: https://github.com/medialab-ufg/tainacan-test-repo)
cobertura de testes: ?
possui integração contínua?: Não
servidor de integração contínua (travis, circleci, etc): None
métricas de código (ex: codeclimate): None

## Empacotamento
é empacotado? Não
sistema(s) de empacotamento (deb, npm, pip, etc): None

## Documentação
possui documentação de usuário? Sim
possui documentação de código? Não
formato da documentação (wiki, markdown, rest, doxygen, etc): PDF(guia de usuário)
possui documentação na internet? PDF no github
endereço: https://github.com/medialab-ufg/tainacan/blob/dev/Manual%20do%20Tainacan%201.1%20-%20novo.pdf

## Comunidade
possui issues abertas no github? Sim
possui issues fechadas? Sim
já aceitou algum pull request? Apenas 1, mas é único pull request que foi feito
número de estrelas: 14
número de forks: 11
utiliza a wiki? Sim, para documentos (Plano de Projeto, Plano de Gerência de Configuração, Plano de Verificação e Validação, Plano de Garantia da Qualidade).
 
## Docker
possui Dockerfile? Não
possui Docker compose? Sim, só para banco de dados. Mas está com configuração dependente do ambiente local de um dos desenvolvedores("Leo").
presente no Docker hub? Não
Dockerfile presente no repositório? Não
Dockerfile em repositório separado? Não
endereço:

## Automação
gerenciador de tarefas (make, rake, inv, gulp, etc): Tem um composer.json que só diz que usa PHP >= 5.2.4
comando de instalação/dependências? None
comando:
comando para inicializar serviço/aplicativo? None
comando:
script para executar testes? None
comando:
script para construir a documentação? None
comando:
script para empacotar? None
comando:

**Comment by fabio1079** [comment]
Issue relacionada: https://github.com/lappis-unb/minc/issues/7

**Comment by fabio1079** [comment]
https://github.com/lappis-unb/minc/blob/document-projects/catalogo-minc/projetos-checklists/tainacan.md
