### ISSUE TITLE
Revisar personalidade do bot

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/EcossistemasSWLivre#51]

**Comment by rodmaia** [comment]
@MatheusFaria revisamos a maior parte dos arquivos. Faltou o [execucao_perguntas_e_respostas_CGEFI.yml](https://github.com/lappis-unb/minc-rouanet-bot/blob/master/training_data/execucao_perguntas_e_respostas_CGEFI.yml).
Se quiserem, podem tentar subir os outros e ver se a gente não quebrou nada ;)

**Comment by joenio** [comment]
temos ainda alguma pendência nessa atividade?

**Comment by rodmaia** [comment]
@joenio não conseguimos revisar 100% das respostas. Precisamos decidir se a responsabilidade sobre o conteúdo continua a encargo do Lappis ou se passa para o MinC, dependendo da estratégia de homologação que vamos adotar.

**Comment by rodmaia** [comment]
Vamos fazer mais uma rodada de revisão da base de conhecimento, mas estruturada de outra forma e com a participação de um(a) profissional de comunicação. 
Por hora, essa atividade está concluída.
