### ISSUE TITLE
Relatório Entrega II

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/EcossistemasSWLivre#53]
Escrita do relatório referente à segunda entrega do projeto (de jan 2018 à março 2018). De acordo com as macros planejadas em:
https://docs.google.com/spreadsheets/d/1zZGTrlYAiDfj4ezYtsOulN9JAc8MWr5eLovIHiih1fw/edit

- [ ] Fazer o template do Relatório da Etapa II, com os principais entregáveis previsto no cronograma acima

- [ ] Delegar para as frentes o preenchimento dos resultados alcançados

- [ ] Fazer o fechamento financeiro do período

- [ ] Abrir o processo para entrega oficial da segunda etapa 

- [ ] Iniciar processo de repasse da segunda parcela do repasse

**Comment by MatheusFaria** [comment]
Algum progresso nesta issue? Já tem algum lugar que as frentes devem preencher?

**Comment by RochaCarla** [comment]
Era para termos organizado isso no planning.. 

Vou colocar o template e delegar via issue..

**Comment by joenio** [comment]
está sendo feito no repositório:

https://github.com/lappis-unb/EcossistemasSWLivre/blob/master/Relatorios/R2/RELAT%C3%93RIO%20ETAPA%202.md

**Comment by RochaCarla** [comment]
- [ ] Roteiro atualizado com o esperado na etapa 2 (De acordo com o cronograma)

- [ ]  @MatheusFaria  pode inserir a atualização referente à rouana?

- [ ]  @marcosronaldo  pode inserir a atualiação referente à API? (na frente legado)

- [ ] @Duerno  pode inserir a atualização da frente ML? (está na frente salic, junto ao bot)

- [ ] @joenio  pode inserir a atualização da frente metodologia? (está na frente catalogo)

- [ ] @rodmaia2099 pode inserir a atualização da frente Promova Cultura (design Sprint)? (está na frente catalogo)

**Comment by MatheusFaria** [comment]
@RochaCarla em qual seção devem ser feitas essas inserções?

**Comment by RochaCarla** [comment]
Entregue para o Minc
