### ISSUE TITLE
documentar avaliação da entrega-01 da frente de pesquisa

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#56]
desdobramento de issue #45.

https://docs.google.com/document/d/1zGkHUpecNdogRq4qJtar1hSu0UpHbDOsVQfMYLj2Ovs/edit

materializar as notas do link acima no próprio repositório pois esses links costumam ficar perdidos no oceano de docs. ver issue #45.

**Comment by MatheusFaria** [comment]
https://github.com/lappis-unb/EcossistemasSWLivre/wiki/Frente-de-Pesquisa
