### ISSUE TITLE
Definir roteiro de homologação interno e externo

### ISSUE THREAD

**Issue by MatheusFaria** [lappis-unb/EcossistemasSWLivre#57]
Definir estratégia e testes para a homologação do bot, tanto pela equipe interna do LAPPIS, quanto pelo pessoal do MinC/SEFIC

**Comment by RochaCarla** [comment]
Issue  #60 criada para a criação do survey

**Comment by ricardopoppi** [comment]
Criada issue #61 sobre o roteiro para a apresentação na sexta 06/abril

**Comment by joenio** [comment]
Explorar três eixos/dimensões no roteiro:

1. percepção geral
1. precisão das respostas
    * se o bot responde certo ou errado
    * extrair número de acertos e erros do log
    * perguntar ao usuário se o bot respondeu de forma certa:
      pouco, médio, muito, muitissimo, etc...
1. fluxo da interação
    * quantos passos para responder?
    * quantidade de balões/caixinhas
    * tamanho do texto / quantidade de texto por balão
    * facilidade pra ler
1. qualidade do conteúdo (próximo survey/etapa)
    * se o texto do bot está bom e compreensível
    * facilidade pra ler
    * nível de detalhes apropriado? muito ou pouco detalhado?

**Comment by joenio** [comment]
exemplos de perguntas a fazer ao chatbot:

1. Aprenda o quanto pode ser deduzido do seu imposto de renda
2. Aprenda o que é a lei de inventivo a cultura.
3. Aprenda o que significa lei rouanet
4. Descubra como submeter seu projeto para arrecadar fundos
5. Aprenda como incentivar um projeto abatendo do imposto X ou Y

**Comment by MatheusFaria** [comment]
Coloquei as perguntas da homologação aqui:
https://github.com/lappis-unb/EcossistemasSWLivre/wiki/Rouana-Homologa%C3%A7%C3%A3o

Não coloquei muitas para não tornar o teste chato e extenso. Porém existem 5 perguntas para cada fluxo possível.

**Comment by ricardopoppi** [comment]
@MatheusFaria @joenio @rodmaia2099 como imaginaram nossa proposta inicial para o processo de homologação? A gente propoe que eles sigam o roteiro e respondam esse formulário em uma semana? A gente consolida os dados em mais uma semana e marcamos reunião pra definir como será a entrada em produção?

Sugestão:
1) Aplicação do roteiro e resposta do formulário (até 13/abril)
2) Consolidação dos dados pelo Lappis e proposta de cenários para produção (aqui aplicaríamos a regra sugerida de 30% - ou outro número deliberado na reunião com SEFIC - de problemas resolvidos  (até 20/abril)
3) Após análises da homologação monta-se o time MinC que vai conduzir a entrada em produção da Rouana, com apoio do Lappis 

Que tal?

**Comment by MatheusFaria** [comment]
Acho que a data de produção depende dos resultados, então é melhor deixar em aberto, e depois que coletarmos os dados nós marcamos a data de colocar em produção.

**Comment by ricardopoppi** [comment]
De acordo @MatheusFaria. O 20 de abril era uma discussão sobre a produção mas acho melhor deixar em aberto também.

**Comment by joenio** [comment]
concordo com o @MatheusFaria quanto a data para produção.

@ricardopoppi em relação a data 13/abril acho que está um bom prazo, mas precisamos apresentar a eles tanto o roteiro quanto o survey entre amanhã (sexta) e segunda dia 09/abril para garantir que não teremos atrasos.

no mais está tudo ok.

@MatheusFaria fiz uma pequena mudança no roteiro, no geral achei bom, vai funcionar muito bem, gostei!

pendente agora criar o survey que será respondido em paralelo ou na sequência do roteiro.

**Comment by RochaCarla** [comment]
O survey está disponível em https://goo.gl/forms/CfxKdVdCK3hLQfZz2
Enviei para vocês a permissão para editar.

**Comment by RochaCarla** [comment]
Lista das pessoas da SEFIC presentes na reunião. A homologação será enviadas para esses contatos:

- [ ] Vicente.filho at cultura.gov.br

- [ ] eduardo.silva at cultura.gov.br

- [ ] andre.ferreira at cultura.gov.br

- [ ] ana.gomes at cultura.gov.br

- [ ] wanderson.lima at cultura.gov.br

- [ ] janete.silva at cultura.gov.br

- [ ] pauliane.sousa at cultura.gov.br

- [ ] leticia.goncalves at cultura.gov.br

**Comment by joenio** [comment]
eu, @ricardopoppi e @peterlima fizemos uma avaliação do roteiro, do survey e do próprio bot, anotamos nossas impressões sobre este teste inicial na issue #62.

**Comment by joenio** [comment]
Fiz uma última revisão no roteiro, alguém pode revisar o texto?

https://github.com/lappis-unb/EcossistemasSWLivre/wiki/Rouana-Homologa%C3%A7%C3%A3o

Após isso precisamos gerar um PDF com o texto pois iremos sugerir que eles sigam este roteiro impresso.

**Comment by joenio** [comment]
a homologação foi iniciada, estamos em fase final. creio que podemos fechar o survey e tirar o bot de homologação do ar até a próxima rodada.

**Comment by joenio** [comment]
iremos aguardar até sexta-feira dia 20/04.
