### ISSUE TITLE
Preencher checklit do Ver Salic

### ISSUE THREAD

**Issue by MatheusMiranda** [lappis-unb/EcossistemasSWLivre#6]
- Avaliar organização do repositório, formas de colaboração e distribuição do projeto;
- Mapear pontos de melhoria;
- Mapear demandas e documentar pontos importantes;

**Comment by joenio** [comment]
iremos tratar disso na frente PromovaCultura, para mais detalhes veja https://github.com/lappis-unb/PromovaCultura
