### ISSUE TITLE
Criar survey para ser aplicado  na homologação da Rouana

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/EcossistemasSWLivre#60]
Fazer o survey para avaliar qualitativamente a homologação da Rouana.

Conteúdo a ser avaliado no survey:

- [ ] Percepção geral da Rouana

- [ ] Performance

- [ ] Fluxo

**Comment by joenio** [comment]
Criar survey online (utilizar google forms por exemplo)

**Comment by joenio** [comment]
Critério de aceitação de homologação de chatbot: 30% dos usuários satisfeitos, ou seja, conseguiram resolver seus problemas.

**Comment by RochaCarla** [comment]
Onde estão os detalhes que conversamos?

**Comment by MatheusFaria** [comment]
https://github.com/lappis-unb/EcossistemasSWLivre/issues/57#issuecomment-378722853

**Comment by RochaCarla** [comment]
O survey está disponível  para ser preenchido em 
https://goo.gl/forms/9oVfCt5YmBPjavpI3

Porém, ainda precisa ser revisado, refatorado e validado (Todos relacionados à issue tem permissão de edição no form)

**Comment by joenio** [comment]
Não encontrei forma de comentar direto do form então vou fazer os comentários por aqui.

## Pergunta: Qual foi a taxa de acerto das respostas dadas pela Rouana?

_Creio que as respostas tão numa escala muito pequena, para o usuário calcular se o bot acertou de 70 à 89 ou de 90 a 100 por exemplo, são intervalos pequenos de apenas 10%. Acho pouco intuitivo e talvez os usuários não saibam responder isso. Creio que melhor seria perguntar algo numa escala mais subjetiva e nós calcularmos o percentual depois olhando os logs, nessa escala subjetiva imagino algo como: o bot acertou pelo menos metade das minhas perguntas ou o bot errou a maior parte das minhas perguntas._

No mais achei que está bom em quantidade de questões e na descrição delas, vamos fazer uma rodada interna após bater o martelo sobre essa primeira versão do roteiro e do survey? Acho que uma primeira rodada entre nós e o resto da equipe envolvida no chatbot nos dará feedback para pequenos ajustes antes de enviar pro MinC.

**Comment by joenio** [comment]
avaliei as respostas dadas até o momento no survey, segue abaixo minhas conclusões:

* 11 respostas

principais problemas apontados nas respostas:

* textos longos, fonte pequena
* dificuldade em entender e chavear entre contextos, usuários não compreendem bem o chaveamento entre contextos
* não consegue responder muitas das dúvidas dos usuários (causa possível: base de conhecimento pequena)
* paleta de cores não segue a identidade do SALIC/Rouanet
* mais de 50% dos participantes ficaram insatisfeitos ao avaliar a conversa geral com o bot
* repetição da apresentação do bot "oi eu sou a assistente virtual ..."
* repetição de despedida, o bot entende que o usuário está terminando a conversa quando está apenas agradecendo pela informação
* apenas 1 pessoa obteve a resposta certa com 1 pergunta

**Comment by joenio** [comment]
segue gráficos com resultados do survey:

![captura de tela de 2018-04-17 16-55-51](https://user-images.githubusercontent.com/44172/38893279-3af0d0fe-4260-11e8-8bd9-0bed12d76f6b.png)

![captura de tela de 2018-04-17 16-56-20](https://user-images.githubusercontent.com/44172/38893308-5369b394-4260-11e8-9c78-9a657a489e66.png)

![captura de tela de 2018-04-17 16-56-55](https://user-images.githubusercontent.com/44172/38893329-5f31e7e6-4260-11e8-8ea1-016cc3167cad.png)

![captura de tela de 2018-04-17 16-57-20](https://user-images.githubusercontent.com/44172/38893364-710c6572-4260-11e8-980e-65ca1d2d29be.png)

![captura de tela de 2018-04-17 16-58-12](https://user-images.githubusercontent.com/44172/38893395-8d983716-4260-11e8-8755-5e70f888bdba.png)

![captura de tela de 2018-04-17 16-58-33](https://user-images.githubusercontent.com/44172/38893406-999b0c6e-4260-11e8-96cb-c8032ad17d67.png)

![captura de tela de 2018-04-17 16-58-55](https://user-images.githubusercontent.com/44172/38893422-a54c5a5e-4260-11e8-85be-81aafcb1fd7e.png)

**Comment by joenio** [comment]
arquivo csv com as respostas (os campos nome e email foram removidos):

* [Lappis-Survey-Rouana-Chatbot.csv.txt](https://github.com/lappis-unb/EcossistemasSWLivre/files/1921399/Lappis-Survey-Rouana-Chatbot.csv.txt)

**Comment by joenio** [comment]
encaminhamentos após análise das respostas do survey e dos logs do bot: #65 #66 #67 #68 #69 #70
