### ISSUE TITLE
Criar roteiro para a apresentação da rouana pra sefic

### ISSUE THREAD

**Issue by ricardopoppi** [lappis-unb/EcossistemasSWLivre#61]

**Comment by ricardopoppi** [comment]
@MatheusFaria @Duerno @izacristina Sugiro que ao longo do dia de amanhã peguem uns minutinhos pra responder as perguntas nesse roteiro, direto no texto. Fiquem a vontade de sugerir o que ficou faltando. Vai ser um bom orientador para a nossa apresentação na sexta.

https://docs.google.com/document/d/1C_dVLrd4aUpdg3Lg_5U8BEahT3YowvAY88OI16yjUGQ/edit?usp=sharing

(cc @RochaCarla @rodmaia2099 @joenio )

**Comment by belaaiza** [comment]
@ricardopoppi será criada uma apresentação mesmo com as informações do doc? tipo um ppt?

**Comment by ricardopoppi** [comment]
@izacristina vou transformar esse texto num markdown na wiki do chatbot,  gente abre ele na hora pra servir como roteiro. pensei nisso na linha da gente sempre focar na produção de materiais que se transformem imediatamente em documentação do produto/comunidade
