### ISSUE TITLE
aplicar o survey internamente com as equipes do chatbot

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#62]
issue relacionada #60

**Comment by joenio** [comment]
gente, vamos colocar nossas impressões sobre o roteiro, sobre o bot e sobre o survey nessa issue.

**Comment by joenio** [comment]
Impressões **sobre o roteiro** e **sobre o bot**:

1. A janela do bot pediu nome e email, não entendi bem o porque.

2. Quando habilita nome/email a mensagem de boas vindas no início da rouane se perde.
   Mas após minha primeira mensagem o bot me enviou a mensagem padrão "Uma assistente virtual, como eu, é um programa de computador..."

3. A interface me identifica como "You", não tem tradução?

4. Fiz uma pergunta direta "o que á lei Rouanet" e ela me peerguntou o que eu gostaria de saber ao invés de me responder diretamente.

5. Quando o bot fala "que bom é meu assunto preferido" eu não sei qual assunto ela entendeu de fato.

6. Perguntei de quais tipos são os projetos aprovados e ela repetiu a resposta sobre o número de projetos.

7. A resposta sobre a SEFIC está muito longa, fala sobre Pronac e CNIC e só depois vem SEFIC, poderia ser o contrário.
   ( ou poderia partir da hipótese que o usuário sabe o que CNIC e Pronac e somente explicar em caso do usuário perguntar )

8. Perguntei "o que é admissibilidade" ela me chamou de Dave e me respondeu algo em ingles.

9. quando perguntei "como cadastrar proponentes" ela me fez pergunta sobre como pode me ajudar
   sendo que eu gostaria de receber uma resposta imediata.

10. falei "esqueça isso" ela respondei "I'm sorry Dave, ..."

11. "como vincular meu cpf" = "I'm sorry Dave.."

12. tá me respondendo muito "I'm sorry..."

13. Entrou em loop e n sai do contexto onde me responde "I'm sorry ..." para tudo

14. O roteiro tá grande, podemos reduzir e juntar algumas perguntas em apenas uma, perguntas mais abrangente,
    creio que precisamos reduzir para 10 perguntas, e colocar nas perguntas uma pergunta numa escala
    de satisfação, se respondeu bem ou não conseguiu de forma alguma responder sobre aquele tema.

**Comment by joenio** [comment]
**sobre o survey**

Respondi o survey e coloquei na própria resposta algumas impressões, precisamos resgatar as respostas para avaliar.

No geral creio que a parte sobre a qualidade das respostas do bot poderia estar associada com as perguntas do roteiro, pois o bot pode responder bem a uma séria de questões gerais sobre a lei rouanet mas responder de forma insatisfatória sobre a captação de recursos para o meu projeto.

**Comment by joenio** [comment]
**Sobre o roteiro:**

* adicionar link para o survey (link fácil de digitar) no roteiro e adicionar instruções básicas convidando o usuário para responder o survey na sequencia do teste
* formatar o roteiro para impressão, adicionar espaço entre as pertuntas para os usuários anotarem impressões gerais, nós podemos solicitar que eles nos entreguem o roteiro com essas anotações
* o roteiro deve conter todas as instruções necessárias para o teste, para o survey, para acessar o bot, etc

**Comment by joenio** [comment]
@peterlima @ricardopoppi coloquem suas impressões nessa issue.

**Comment by ricardopoppi** [comment]
Sobre o survey, ajustei diretamente incluindo nome, email e diminuindo a escala de 10 pra 5

1) Aprimorar o contexto de agradecimento, sem necessariamente ser o final da conversa, mais como reação às informações que ela passa. tipo: legal/gostei/puxa não sabia/etc. Atualmente quando escrevo "obrigado" a Rouana automaticamente entende como fim de conversa e já pede pra dar nota.

2) Na hora da nota ela aceita qualquer conteúdo como nota, mesmo que não seja nota. Eu tentei continuar a conversa ela agradeceu pela nota.

3) Duvida sobre como submeter projeto ela confundiu com dúvidas sobre OS PROJETOS como indicadores etc - sugestão: melhorar nos expects a forma de entrar nesse contexto

**Comment by peterlima** [comment]
1 - A Rouana não possui mensagem de Boas Vindas ou similar.

2 - A janela do bot começa vazia e sem avatar ou mensagem aparecendo
Durante a pergunta e respectiva resposta:

O que é Lei Rounet?
Legal! O que você gostaria de saber sobre ela?*
Apareceu uma outra pergunta em vez de enviar uma resposta.

3 - A Rouana não conseguiu responder "Qual o papel da Sefic?", após eu realizar perguntas aleatórias anteriores.
Como resposta o robô enviou um texto em inglês:
  I'm sorry Dave, I'm afraid I can't do that =/

4- Quando é realizada uma pergunta "vaga" como:
"Fiz uma proposta de projeto."

A Rouana envia uma mensagem em inglês:
  I'm sorry Dave, I'm afraid I can't do that =/

5- Quando perguntado:
Como liga cnpj ao cpf?
Aparece mensagem em inglês:
I'm sorry Dave, I'm afraid I can't do that =/

6 - Quando a Rouana responde:
"Desculpa, sou uma assistente virtual em fase experimental.
às vezes não entendo certos comentários..."
A palavra "comentários" nem sempre é adequada.
Sugiro substituir por:
"às vezes não entendo certas mensagens..."

7- Após perguntar "Qual banco posso abrir conta do projeto?"
A Rouana não está sabendo responder. "Não entendi, Como assim?"

**Comment by joenio** [comment]
**sobre a página de homologação** rouana.lappis.rocks

* Adicionar mais um link para o formulário/survey ao final da página
* Adicionar checkbox ao lado de cada objetivo de aprendizagem e instruir os usuários a marcar quando obtiver sucesso, ou seja, quando conseguirem aprender com o bot o objetivo de aprendizagem
* Adicionar links para o repositório e para os arquivos utilizados no treinamento do bot, criar parágrafo explicando o que significa cada link

**Comment by joenio** [comment]
para registro, endereço do ambiente e roteiro para homologação: https://rouana.lappis.rocks/

fechando issue uma vez que já aplicamos internamente o roteiro, o survey, e também implementamos ou tomamos notas da maioria das impressões registradas aqui.
