### ISSUE TITLE
Produzir e enviar mensagem para a SEFIC com as instruções de homologação

### ISSUE THREAD

**Issue by ricardopoppi** [lappis-unb/EcossistemasSWLivre#63]
Conteúdo da mensagem (contatos coletados na reunião estão na issue #57 )

1) Roteiro de homologação: https://github.com/lappis-unb/EcossistemasSWLivre/wiki/Rouana-Homologa%C3%A7%C3%A3o (devemos entregar ou pedir que imprimam para evitar que tenham de mudar de abas no navegador enquanto interagem com o bot)

2) Survey para responder após execução do roteiro: https://goo.gl/forms/CfxKdVdCK3hLQfZz2 (precisamos gerar um link curto fácil de digitar para incluir o endereço do link no roteiro impresso)

3) Pedido para que consolidem internamente um documento com novas perguntas e respostas, no seguinte formato:
- Assunto específico
- Exemplos de perguntas (podem ser várias, mas todas devem ter a mesma resposta)
- Resposta (deve ser uma só. se for longa, dividir em frases menores)

4) Reforçar que o prazo final da homologação é sexta-feira (13/abril). Informar que as conversas da Rouana estão sendo gravadas e que esse conteúdo será usado nas análises que faremos.

**Comment by ricardopoppi** [comment]
Sugestão de mensagem:

Prezados, conforme encaminhamos na apresentação de sexta, segue em anexo o roteiro de homologação da Rouana. Sugerimos imprimir este documento para facilitar o processo.

Esse trabalho consiste em duas tarefas:

**TAREFA 1**
Durante a homologação, mantenha aberto dois links:
1) Link da Rouana: https://rouana.lappis.rocks/
2) Link do survey para responder após a realização do roteiro: https://goo.gl/forms/CfxKdVdCK3hLQfZz2
 
**TAREFA 2**
Também sugerimos que consolidem internamente um documento com novas perguntas e respostas a serem incluidas nos arquivos de treinamento do bot. As sugestões devem vir no seguinte formato:  
a) Assunto específico  
b) Exemplos de perguntas (podem ser várias, mas todas devem ter a mesma resposta)  
c) Resposta (deve ser uma só. se for longa, dividir em frases menores)  

Relembramos que o prazo final da homologação é essa sexta-feira (13/abril). Se precisarem de adiamento nos avisem. Informamos que as conversas da Rouana estão sendo gravadas e que esse conteúdo também será usado nas análises que faremos.

**Comment by joenio** [comment]
creio que fechamos essa issue, farei um bate-papo com o matheus faria agora para começar análise das respostas do survey e logs produzidos no período da homologação.
