### ISSUE TITLE
reduzir tamanho dos textos das respostas da atual base de conhecimento

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#65]
(precisamos encontrar uma solução, mesmo que seja delegar pro minc ou outros atores)

um sistema para gestão do conhecimento integrado ao FAQ do MinC irá mitigar numa certa escala este problema, mas não irá resolver.

**Comment by ricardopoppi** [comment]
Aqui talvez entre aquele perfil de design instrucional. A questão é decidir como resolver no curto prazo (rouana com hubot-nature) mas também decidir se vale a pena o lappis incorporar esse perfil. Eu acho que vale, porque esse elemento é intrínseco ao produto que estamos desenvolvendo.

**Comment by joenio** [comment]
exato, o ideal é ter alguém na equipe pois creio que precisaremos ter cuidado constante com a base de conhecimento, perguntas, respostas, tamanho dos textos, redação, etc, etc.

no curto prazo precisamos bater um papo presencial para pensar em soluções, eu não vejo nenhuma boa solução aqui.
