### ISSUE TITLE
repensar o fluxo de interação com o bot

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#69]
como proposta incial podemos criar um menu explícito para que usuários entendam que primeiro precisa entrar num dos itens do "menu"   e dessa forma também consigam voltar ao menu principal

**Comment by ricardopoppi** [comment]
creio que essa é a melhor forma de ter uma produção segura com a Rouana usando hubot nature. Estou de acordo com essa solução

**Comment by RochaCarla** [comment]
Sugestão de Leitura:
https://medium.com/labworks-io/the-conversation-designers-handbook-or-how-to-design-chatbots-google-home-actions-and-alexa-17ebb87b332c

https://chatbotsmagazine.com/6-tips-for-designing-your-best-chatbot-591aba9c9eff

https://chatbotsmagazine.com/cheat-sheet-all-facebook-chatbot-interactions-4b14e4e00178
