### ISSUE TITLE
Avaliar análise do survey com os gestores Minc

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/EcossistemasSWLivre#72]
- [ ] A análise dos surveys podem ser acessado em:
https://github.com/lappis-unb/EcossistemasSWLivre/tree/master/Relatorios/R2/anexos

- [ ] Identificar os pontos de melhoria

- [ ] Criar issues com as melhorias

- [ ] Dar feedback para os envolvidos

**Comment by joenio** [comment]
vamos manter uma única issue incluindo analise dos dados de seniores e gestores #73
