### ISSUE TITLE
Avaliar a análise do survey realizado com os seniores e gestores

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/EcossistemasSWLivre#73]
- [ ]  A análise dos surveys podem ser acessado em:
https://github.com/lappis-unb/EcossistemasSWLivre/tree/master/Relatorios/R2/anexos

- [ ]   Identificar os pontos de melhoria

- [ ]  Criar issues com as melhorias

- [ ]  Dar feedback para os envolvidos

**Comment by joenio** [comment]
merge com a issue #72

**Comment by joenio** [comment]
os documentos com os dados e análise estão em:
* https://github.com/lappis-unb/EcossistemasSWLivre/tree/master/resultados-da-frente-pesquisa/entrega-02-dados-seniors

**Comment by joenio** [comment]
Notas e ações a tomar sobre o relatório **Resultados de pesquisa com desenvolvedores Seniores do projeto UnB/MinC**:
1. promover maior interação entre seniores e alunos
1. avaliar se estamos usando um processo de desenvolvimento adequado uma vez que apenas 61% concordam com o atual processo
1. considerar o conhecimento técnico na definição de metas estratégicas do projeto
1. as issues ainda possuem baixo índice de utilização, apenas metade utiliza para comunicação
1. disseminar os conceitos do software livre, há pouca compreensão sobre o tema

**Comment by joenio** [comment]
Notas e ações a tomar sobre o relatório **Resultados de pesquisa com gestores do projeto UnB/MinC**:
1. divulgar (e garantir que houve entendimento) a todos os gestores do MinC sobre a estrutura do projeto, canais de comunicação, andamento, progresso, entregas, etc
1. promover maior uso e adesão da lista de discussão do projeto, especialmente entre os gestores do MinC (o relatório afirma que não há lista inclusive, mas temos sim um grupo no google groups em https://groups.google.com/d/forum/lappis-minc)

**Comment by joenio** [comment]
@RochaCarla dá uma olhada nos comentários acima e complementa caso note que faltou capturar algo importante para melhoria no nosso processo.
