### ISSUE TITLE
preparar apresentação sobre chatbot na caixa cultural

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#78]
no dia 30 de maio as 13h o laboratório irá apresentar o chatbot na caixa cultural, vamos registrar aqui os encaminhamentos a respeito dessa apresentação, pessoas, confirmação de horário, etc.

**Comment by joenio** [comment]
teremos reunião amanhã quinta dia 24 via hangout às 9h-10h para planejar e definir os detalhes e formato da apresentação @rodmaia2099 @ricardopoppi @RochaCarla

**Comment by RochaCarla** [comment]
1- apresentar o laboratório
2 - evolução do laboratório
3 - caso minc + ej

timebox (cerca de 30 min)

demo hubot natural
demo rasa

**Comment by RochaCarla** [comment]
- [ ] Apresentação Lappis história - Carla + Poppi

- [ ] Modelo de trabalho - tanto interno (alunos) - Carla + Joênio + Maia

- [ ] Modelo de trabalho -  externo  -- Poppi

- [ ] Case Rouana - Ministério da Cultura - Faria - uma das coisas que estamos fazendo no minc
evolução do hubot-natural -> Rasa
caminho feliz da homologação + caminho triste
montar um caminho feliz no rasa que cobre o caminho triste do Hubot/natural
o que identificamos no rasa que cobre os requisitos (exemplo de agendamento para "amanhã")

**Comment by ricardopoppi** [comment]
@RochaCarla @rodmaia2099 @joenio @MatheusFaria forkei o modelo pra gente trabalhar no mesmo arquivo, tudo bem? Aqui > https://docs.google.com/presentation/d/1KAQ6D4VSMtUXpf5ytMdhE57xsiXwJ9rO0ElelOo02rQ

**Comment by rodmaia** [comment]
Fiz algumas modificações mas o documento precisa de uma boa renovada. Sugiro realinharmos na segunda-feira e fazer uma nova rodada de ajustes. Na quarta podemos nos reunir mais cedo para repassar o material e alinhar o discurso. Que tal @RochaCarla @ricardopoppi @joenio @MatheusFaria ?

**Comment by RochaCarla** [comment]
Atualizei o conteúdo dos projetos + história do lab.. mas concodo com @rodmaia2099

**Comment by rodmaia** [comment]
Comecei a refazer a formatação da apresentação mas ainda faltaram alguns slides

**Comment by rodmaia** [comment]
Done!
