### ISSUE TITLE
Promover e organizar a Lab Conf

### ISSUE THREAD

**Issue by ricardopoppi** [lappis-unb/EcossistemasSWLivre#79]
Proposta preliminar: https://docs.google.com/document/d/1eB_04h09EQZ3ivAOfRWpoJjLThP5ZcTMFojftDsYMuQ/edit?usp=sharing

Próximos passos:
- [x] Fechar a data pra 9 de agosto e reservar o local com Marcus (Minc)
- [x] Terminar de fechar a proposta conceitual
- [x] Articular a logística com os outros labs
- [x] Fazer o planejamento das frentes conjuntas para o evento
- [x] Fechar a lista de convidados para as duas mesas mesas

**Comment by joenio** [comment]
o lab foi um sucesso, temos a pendencia agora de editar os vídeos (issue: https://gitlab.com/lappis-unb/athena/issues/52)
