### ISSUE TITLE
Preencher checklit e-pracas

### ISSUE THREAD

**Issue by fabio1079** [lappis-unb/EcossistemasSWLivre#8]

**Comment by fabio1079** [comment]
# Checklist

## Básico
projeto: e-pracas
repositório: https://github.com/culturagovbr/e-pracas
linguagem principal: JS
plataforma (web, mobile, desktop, etc): web

## Readme
posui readme? No
formato do readme (md, txt, rst, etc): None
badges presentes no readme: None

## Integração contínua
possui testes? No
cobertura de testes: 0%
possui integração contínua? No
servidor de integração contínua (travis, circleci, etc): None
métricas de código (ex: codeclimate): None

## Empacotamento
é empacotado? No
sistema(s) de empacotamento (deb, npm, pip, etc): Apenas npm paras as usas dependências.

## Documentação
possui documentação de usuário? No
possui documentação de código? No
formato da documentação (wiki, markdown, rest, doxygen, etc): None
possui documentação na internet? No
endereço: None

## Comunidade
possui issues abertas no github? Sim
possui issues fechadas? Sim
já aceitou algum pull request? No
número de estrelas: 1
número de forks: 1
utiliza a wiki? No
 
## Docker
possui Dockerfile? No
possui Docker compose? No
presente no Docker hub? No
Dockerfile presente no repositório? No
Dockerfile em repositório separado? No
endereço: None

## Automação
gerenciador de tarefas (make, rake, inv, gulp, etc): gulp
comando de instalação/dependências? No?
comando: Não está no scripts do packages.json
comando para inicializar serviço/aplicativo? No ?
comando: Não está no scripts do packages.json
script para executar testes? No
comando: None
script para construir a documentação? No
comando: None
script para empacotar? No
comando: None

**Comment by joenio** [comment]
@fabio1079  @RochaCarla  esse checklits foi repassado para o minc? estou fechando a issue, seria bom garantir que este conhecimento chegou ao minc de alguma forma.
