### ISSUE TITLE
Relatório de Entrega 3

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/EcossistemasSWLivre#83]
Atualizar os avanços realizados pelas frentes no período de abril à julho 2018

- [ ] Rouana - Estudo de UX (Colocar os relatórios realizados e o fluxo proposto - versões)
- [ ] Rouana - Conector Rasa + testes rasa

- [ ] Salic ML - Levantamento de requisitos (Reuniões e diagnostico dos principais pontos de melhoria possíveis para usar algoritmo de aprendizagem de maquina)

- [ ] Salic ML - Proposta Salic ML

- [ ] Experimentos SALIC ML - Quais foram os dados e os experimentos exploratórios realizados

- [ ] Governança - SEFIC + CGTEC - LABconf planejamento (levantamento das inovações realizadas durante o período no LAPPIS)

- [ ] Aferição de qualidade - relatório com o levantamento bibliografico

- [ ] Devops  -  evolução do pipeline + ?

https://github.com/lappis-unb/EcossistemasSWLivre/tree/master/Relatorios/R3

**Comment by RochaCarla** [comment]
@marcusvinicus

**Comment by MatheusFaria** [comment]
## Rouana - Assistente Virtual da Cultura

Após os testes, junto a SEFIC, na entrega anterior, foram analisados os resultados. Estes resultados mostram que houveram muitas falhas de usabilidade, de contéudo e de tecnologia. As falhas de usabilidade dizem respeito sobre como o usuário reage as coisas que a assistente fala, a maior parte dos usuários não conseguiram manter uma conversa fluida e não chegaram no objetivo deles. As falhas de conteúdo dizem respeito sobre os textos utilizados pela assistente, eles se mostraram muito longos e técnicos, não contribuindo para a fluidez da conversa. As falhas de tecnologia dizem respeito sobre a tecnologia hubot-natural que se mostrou incapaz de analisar algumas palavras e contextos em portugês do brasil, pois ela é voltada para o português de portugal, impossibilitando alguns fluxos de conversa.

Para atacar estes problemas, foram necessárias algumas ações. O problema de usabilidade foi trabalhado fazendo-se um estudo sobre a usabilidade em chatbots, principalmente na parte do chatbot guiar a conversa para achar a resposta correta para o usuário. Um relatório com o resumo do estudo foi elaborado:

https://github.com/lappis-unb/EcossistemasSWLivre/wiki/Estudo-sobre-melhores-pr%C3%A1ticas-de-bots

Após o estudos, conduzimos um experimento de elaboração de possíveis fluxos de conversas no contexto da nossa assistente virtual. Tivemos no total 5 iterações, onde cada iteração eram conduzidos testes com um grupo de usuários. Os testes eram conduzidos sem a tecnologia, eram feitas as perguntas para o usuário utilizando uma ferramenta de chat, para simular ao máximo o ambiente real que o usuário encontraria. A cada teste, os usuários repondiam um questionário, e os resultados compilados eram utilizados para gerar a próxima versão do fluxo.

!! IMAGENS DOS FLUXOS !!

O problema relativo a tecnologia foi resolvido com o uso de outra tecnologia, o Rasa. Esta tecnologia se mostrou mais capaz em resolver os problemas que estamos enfrentando com a tecnologia anterior. Porém esta tecnologia não se conecta a nossa plataforma de chat, RocketChat, a qual não foi trocada. Para resolver isso, tivemos que desenvolver um conector entre o Rasa e o RocketChat. Este connector será incluido, como contribuição, para a comunidade do Rasa, possibilitando qualquer pessoa utilizar esta nossa solução assim que for utilizar o Rasa.

Além do conector, foram feitos testes de algumas funcionalidades do Rasa. Diferente da tecnologia antiga, o Rasa possui várias funcionalidades a mais para o auxilio de desenvolimento de chats. Para saber o que era possível ou não adicionar na nossa assistente virtual, foram feitos testes de algumas funcionalidades. Estes testes foram feitos através da leitura da documentação e da interação direta com a comunidade do Rasa, que se mostrou mais solicita e populosa que a comunidade da tecnologia anterior.

**Comment by joenio** [comment]
o relatório já foi feito e entregue pela @RochaCarla
