### ISSUE TITLE
Preparar workshop de devops para LabConf dia 31/agosto, 14hs

### ISSUE THREAD

**Issue by ricardopoppi** [lappis-unb/EcossistemasSWLivre#84]
Duração do workshop: 1,5h
Título do workshop: DevOps com Docker e Rancher do case EJ/MinC: Como transformar um software em SaaS usando DevOps (Time DevOps Lappis)
Descrição do workshop: Nesse workshop você poderá conhecer os caminhos para efetuar a transformação de um software em SaaS, realizando também sua entrega contínua em ambientes de homologação e produção usando tecnologias de ponta da indústria como Docker e o orquestrador de contêineres Rancher, através da metodologia GitFlow e serviços de Integração Contínua.

**Comment by ricardopoppi** [comment]
@guilacerda e @pablodiegoss combinamos com a @RochaCarla que vcs tocariam esse workshop. Procurem o @joenio para maiores detalhes

**Comment by joenio** [comment]
@guilacerda @pablodiegoss o que vcs pensaram pro workshop?

**Comment by joenio** [comment]
os workshops foram realizados na labconf, fechando issue
