### ISSUE TITLE
Preparar lighting talks de 7 minutos para LabConf dia 31/agosto, 15h30

### ISSUE THREAD

**Issue by ricardopoppi** [lappis-unb/EcossistemasSWLivre#85]
- [ ] Enfrentando legados, e agora? Como achar a ponta do durex (Time ML Lappis)
- [ ] Ensinando um app a pensar: Fluxo para bot usando IA (Time Chatbot Lappis, @brunapinos)
- [ ] Sou roteirista! De Bot! (Paloma/Time Chat bot Lappis, @palomacmamede)
- [ ] Power Trios: do rock 'n' roll ao ágil (Time Promova Lappis, @rodmaia2099 @peterlima)

**Comment by ricardopoppi** [comment]
@palomacmamede sobre a sua palestra: pensamos que como é uma palestra de 7 minutos poderia ser algo como "3 ou 5 coisas que uma roteirista de bot tem que saber". O que acha?

**Comment by ricardopoppi** [comment]
Sobre a lightining de legados, tem a fala da @RochaCarla:
(i) Legacy-in-a-box com API
(ii) Micro serviços
(iii) Plugins de browser

Será que vc não é quem dá essa palestra @RochaCarla?

**Comment by joenio** [comment]
doc com detalhes sobre a LabConf: https://docs.google.com/document/d/1eB_04h09EQZ3ivAOfRWpoJjLThP5ZcTMFojftDsYMuQ/edit?ts=5b5f0fda

**Comment by joenio** [comment]
vamos ensaiar as apresentações na próxima MiniLappisConf: https://lappis-unb.github.io/minilappisconf/

**Comment by palomacmamede** [comment]
@ricardopoppi acho ótimo (: acho que dá pra fazer algo legal seguindo essa temática!

**Comment by ricardopoppi** [comment]
@palomacmamede oba, então formô!

**Comment by joenio** [comment]
feito
