### ISSUE TITLE
Preparar os showcases para a LabConf dia 31 de Agosto, 10hs

### ISSUE THREAD

**Issue by ricardopoppi** [lappis-unb/EcossistemasSWLivre#86]
- [ ] Produto ML para recomendações do processo da Lei Rouanet  (Time ML Lappis) = @Duerno @danielgs83 @RochaCarla 
- [ ] Assistente Virtual Taís usando IA (Time Assistente Virtual Lappis) = @MatheusFaria @brunapinos @MatheusMiranda 
- [ ] Salic API: refatoração e instrumentação (Time API) = @marcosronaldo @LucianoPC

**Comment by joenio** [comment]
Tempo de cada showcase = 15 minutos

**Comment by joenio** [comment]
* Dinâmica da apresentação: Apresentações de 15 minutos, focada em tecnologias desenvolvidas ou aprimoradas pelos Labs
* Objetivo: Mostrar alguns resultados concretos do trabalho dos Laboratórios
