### ISSUE TITLE
Conceber um flyer pra LabConf

### ISSUE THREAD

**Issue by ricardopoppi** [lappis-unb/EcossistemasSWLivre#88]
## Conteúdo do flyer:

Lab Conf - Conferência dos Laboratórios de inovação da Cultura
31/agosto
Ministério da Cultura, no Edifício Parque da Cidade Corporate, 12º andar

PROGRAMAÇÃO:

9hs - Chegada dos participantes

10hs - Showcase dos Labs

- Acervos em Rede, interoperabilidade e Web Semântica com Tainacan (Professor Dalton Martins)
- Assistente Virtual Taís usando IA (Time Assistente Virtual Lappis)
- Manutenção e Evolução de Software Legado (Time UFABC)
- Produto ML para recomendações do processo da Lei Rouanet  (Time ML Lappis)
- Produto Salic API: refatoração e instrumentação (Time API)

12hs - Almoço

14:00h - Workshops técnicos

- DevOps com Docker e Rancher do case EJ/MinC: Como transformar um software em SaaS usando DevOps (Time DevOps Lappis)
- Conhecendo o Vue JS e criando sua primeira aplicação (Time UFG)

15:30 - Lightning talks dos times internos dos labs (máx 7 min cada time)

- Enfrentando legados, e agora? Como achar a ponta do durex (Time ML Lappis)
- Ensinando um app a pensar: Fluxo para bot usando IA (Time Chatbot Lappis)
- Sou roteirista! De Bot! (Time Chat bot Lappis)
- Power Trios: do rock 'n' roll ao ágil (Time Promova Lappis)
- "Tem backup!? Sim, Bacula!" - Um breve relato da experiência de utilização do software Bacula em rotinas de backup no MediaLab/UFG (Time UFG)
- Causo de Engenheiro: transições de paradigma no desenvolvimento do SALIC (Time LabLivre/UFABC)

17hs - Roda de conversa sobre contratação de software no governo
Debatedores/as:
Adriano Nunes (MRE/Ateliê de Software)
Aline Santos (Pesquisadora/Anac)
Hilmer Neri (Lappis/UnB)
Leonardo Germani (Pesquisador do tema/Time UFG)
Nayanne Araújo (Presidência da República/Identidade Digital de Governo)

18hs - Roda de conversa sobre adoção de software livre por governos
Debatedores/as:
Carla Rocha (Lappis/UnB)
Jerônimo (UFABC)
Marcus Menezes (CGTEC Minc)
Marisa Souza (MPOG/SETIC)

## Briefing (ṕra ajudar na concepção)

Antecedentes: A parceria entre os órgãos da administração pública e as universidades, materializado pelo instrumento do TED (Termo de execução descentralizada) faz com que a pesquisa e inovação subsidiem o desenvolvimento das tecnologias que dão suporte às políticas públicas no Brasil. O Ministério da Cultura, nos últimos anos tem usado esse instrumento com resultados expressivos na qualidade dos softwares desenvolvidos e na geração de valor para a administração pública e a cidadania.

Objetivos da Lab Conf: A parceria entre o Ministério da Cultura e as Universidades é regida por um plano de trabalho previsto em cada TED. Embora haja algumas metas e atividades em sinergia, a articulação entre o trabalho das universidades tem sido pontual. Por isso propomos a Lab Conf, no sentido de proporcionar, durante um dia de atividades, um ambiente de trabalho conjunto para propiciar 

(i) aumentar o conhecimento da CGTEC e áreas finalísticas do MinC sobre o trabalho dos laboratórios e os produtos e entregas em que estão trabalhando e 

(ii) oferecer às equipes técnicas a oportunidade de compartilhar conhecimentos e metodologias de trabalho através de workshops e lightning talks.

A Lab Conf tem o potencial de fortalecer o contato entre os alunos e profissionais envolvidos nos diversos projetos de modo a criar uma dinâmica contínua de colaboração no atendimento das necessidades de cada TED e do conjunto do ministério.

Além dos objetivos mais voltados ao contexto específico do Ministério da Cultura, a Lab Conf pode promover pontualmente uma discussão técnica sobre os instrumentos de contratação de software em voga no Governo Federal, discutindo experiências recentes e inovadoras como o uso do Ateliê de Software e os próprios TEDs. Será uma oportunidade para a Coordenação de Tecnologia do MinC apresentar preliminarmente o uso que o órgão está fazendo do modelo, junto com outros coordenadores convidados para o debate.

**Comment by joenio** [comment]
![artboard 2labconf](https://user-images.githubusercontent.com/44172/45970267-7501e880-c00c-11e8-9cd2-2b317bd6c374.png)
